-- ============================================
-- 45_cortex_threads_history.sql
-- Optional: cache Cortex thread history in Snowflake
-- ============================================

USE DATABASE PROJECT_DB;
USE SCHEMA APP;

SELECT * FROM CORTEX_CHAT_SESSIONS;

-- Stores thread metadata snapshots (from Threads API list/describe)
CREATE TABLE IF NOT EXISTS CORTEX_THREADS (
  THREAD_ID NUMBER NOT NULL,
  THREAD_NAME STRING,
  ORIGIN_APPLICATION STRING,
  CREATED_ON TIMESTAMP_NTZ,
  UPDATED_ON TIMESTAMP_NTZ,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (THREAD_ID)
);

-- Stores thread message snapshots (from Threads API describe)
CREATE TABLE IF NOT EXISTS CORTEX_THREAD_MESSAGES (
  THREAD_ID NUMBER NOT NULL,
  MESSAGE_ID NUMBER NOT NULL,
  PARENT_ID NUMBER,
  ROLE STRING,
  MESSAGE_PAYLOAD STRING,
  REQUEST_ID STRING,
  CREATED_ON TIMESTAMP_NTZ,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (THREAD_ID, MESSAGE_ID)
);

-- Optional mapping between a client conversation and a Cortex thread
CREATE TABLE IF NOT EXISTS CORTEX_CONVERSATIONS (
  CONVERSATION_ID STRING NOT NULL,
  THREAD_ID NUMBER NOT NULL,
  LAST_ASSISTANT_MESSAGE_ID NUMBER,
  ORIGIN_APPLICATION STRING,
  CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CONVERSATION_ID)
);
