name: Check Source Branch

on:
    pull_request:
        branches: [main]

jobs:
    check-source:
        runs-on: ubuntu-latest
        steps:
            - name: Verify dev branch source
              if: github.base_ref == 'main' && github.head_ref != 'dev'
              run: |
                  echo "Error: Only 'dev' can be rebased into 'main'."
                  exit 1
